development:
  AWS_ACCESS_KEY_ID: "PASTE KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "railsfinalecommstore"
test:
  AWS_ACCESS_KEY_ID: "PAST KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "railsfinalecommstore-test"
production:
  AWS_ACCESS_KEY_ID: "PAST KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "railsfinalecommstore-prod"
