development:
  AWS_ACCESS_KEY_ID: "AKIAIKZ2EQ3TPVKAIXUA"
  AWS_SECRET_ACCESS_KEY: "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"
  S3_BUCKET: "railsfinalecommstore"
test:
  AWS_ACCESS_KEY_ID: "PAST KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "railsfinalecommstore-test"
production:
  AWS_ACCESS_KEY_ID: "PAST KEY ID HERE"
  AWS_SECRET_ACCESS_KEY: "PASTE SECRET ACCESS KEY HERE"
  S3_BUCKET: "railsfinalecommstore-prod"
